name: the_very_unique_weather_app_merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        name: setup pnpm and install dependencies
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: build
        run: pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: deploy to Firebase production
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_VERY_UNIQUE_WEATHER_APP }}'
          channelId: live
          projectId: praisetompane-toy-weather-app
